let data = [
  {
    id: "1",
    avatar: "../../logos/Avatar.svg",
    name: "John Doe",
    msg: "Hello, how are you?",
    time: "09:00",
  },
  {
    id: "2",
    avatar: "../../logos/Avatar.svg",
    name: "Jane Smith",
    msg: "I'm doing great, thanks!",
    time: "09:15",
  },
  {
    id: "3",
    avatar: "../../logos/Avatar.svg",
    name: "David Johnson",
    msg: "What are you up to today?",
    time: "09:30",
  },
  {
    id: "4",
    avatar: "../../logos/Avatar.svg",
    name: "Emily Wilson",
    msg: "I have a meeting in the afternoon.",
    time: "10:00",
  },
  {
    id: "5",
    avatar: "../../logos/Avatar.svg",
    name: "Michael Brown",
    msg: "Any plans for the weekend?",
    time: "10:30",
  },
  {
    id: "6",
    avatar: "../../logos/Avatar.svg",
    name: "Olivia Taylor",
    msg: "I'm going to a concert on Saturday.",
    time: "11:00",
  },
  {
    id: "7",
    avatar: "../../logos/Avatar.svg",
    name: "William Anderson",
    msg: "Can you help me with this problem?",
    time: "11:30",
  },
  {
    id: "8",
    avatar: "../../logos/Avatar.svg",
    name: "Sophia Martinez",
    msg: "Sure, what do you need assistance with?",
    time: "12:00",
  },
  {
    id: "9",
    avatar: "../../logos/Avatar.svg",
    name: "James Davis",
    msg: "I'm having lunch with a friend.",
    time: "12:30",
  },
  {
    id: "10",
    avatar: "../../logos/Avatar.svg",
    name: "Ava Johnson",
    msg: "Let's catch up soon!",
    time: "13:00",
  },
  ,
  {
    id: "11",
    avatar: "../../logos/Avatar.svg",
    name: "Jane Smith",
    msg: "I'm doing great, thanks!",
    time: "09:15",
  },
  {
    id: "12",
    avatar: "../../logos/Avatar.svg",
    name: "David Johnson",
    msg: "What are you up to today?",
    time: "09:30",
  },
  {
    id: "13",
    avatar: "../../logos/Avatar.svg",
    name: "Emily Wilson",
    msg: "I have a meeting in the afternoon.",
    time: "10:00",
  },
  {
    id: "14",
    avatar: "../../logos/Avatar.svg",
    name: "Michael Brown",
    msg: "Any plans for the weekend?",
    time: "10:30",
  },
  {
    id: "15",
    avatar: "../../logos/Avatar.svg",
    name: "Olivia Taylor",
    msg: "I'm going to a concert on Saturday.",
    time: "11:00",
  },
  {
    id: "16",
    avatar: "../../logos/Avatar.svg",
    name: "William Anderson",
    msg: "Can you help me with this problem?",
    time: "11:30",
  },
  {
    id: "17",
    avatar: "../../logos/Avatar.svg",
    name: "Sophia Martinez",
    msg: "Sure, what do you need assistance with?",
    time: "12:00",
  },
  {
    id: "18",
    avatar: "../../logos/Avatar.svg",
    name: "James Davis",
    msg: "I'm having lunch with a friend.",
    time: "12:30",
  },
  {
    id: "19",
    avatar: "../../logos/Avatar.svg",
    name: "Ava Johnson",
    msg: "Let's catch up soon!",
    time: "13:00",
  },
];

export default data;
