let machine = [
  {
    id: "1",
    processId: "1",
    name: "GoodWay",
    title: "Production Machine",
    puantaj: 125,
    nodeId: "node_01",
    serialNo: "ABC123456",
    maxPersonal: 5,
  },
  {
    id: "2",
    processId: "2",
    name: "UPU",
    title: "Assembly Line",
    puantaj: 90,
    nodeId: "node_02",
    serialNo: "DEF789012",
    maxPersonal: 8,
  },
  {
    id: "3",
    processId: "3",
    name: "Baca",
    title: "Testing Equipment",
    puantaj: 75,
    nodeId: "node_03",
    serialNo: "GHI345678",
    maxPersonal: 3,
  },
  {
    id: "4",
    processId: "4",
    name: "Makina",
    title: "Packaging Station",
    puantaj: 110,
    nodeId: "node_04",
    serialNo: "JKL901234",
    maxPersonal: 6,
  },
  {
    id: "5",
    processId: "5",
    name: "Embedded",
    title: "Quality Control",
    puantaj: 80,
    nodeId: "node_05",
    serialNo: "MNO567890",
    maxPersonal: 4,
  },
  {
    id: "6",
    name: "IOT",
    processId: "6",
    title: "Maintenance Unit",
    puantaj: 95,
    nodeId: "node_06",
    serialNo: "PQR123456",
    maxPersonal: 2,
  },
  {
    id: "7",
    processId: "7",
    name: "IIOT",
    title: "Robotics System",
    puantaj: 120,
    nodeId: "node_07",
    serialNo: "STU789012",
    maxPersonal: 10,
  },
  {
    id: "8",
    processId: "8",
    name: "WebApp",
    title: "Material Handling",
    puantaj: 85,
    nodeId: "node_08",
    serialNo: "VWX345678",
    maxPersonal: 7,
  },
  {
    id: "9",
    processId: "9",
    name: "Welding",
    title: "Printing Press",
    puantaj: 100,
    nodeId: "node_09",
    serialNo: "YZA901234",
    maxPersonal: 4,
  },
  {
    id: "10",
    processId: "10",
    name: "Export",
    title: "Packaging Machine",
    puantaj: 70,
    nodeId: "node_10",
    serialNo: "BCD567890",
    maxPersonal: 5,
  },
];

export default machine;
